/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as AppRevisionRouteImport } from './routes/_app.revision'
import { Route as AppOrganizacionRouteImport } from './routes/_app.organizacion'
import { Route as AppObligacionesRouteImport } from './routes/_app.obligaciones'
import { Route as AppDocumentosRouteImport } from './routes/_app.documentos'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAuditoriaRouteImport } from './routes/_app.auditoria'
import { Route as AppAlertasRouteImport } from './routes/_app.alertas'
import { Route as AppColaboradoresIndexRouteImport } from './routes/_app.colaboradores.index'
import { Route as AppColaboradoresNuevoManualRouteImport } from './routes/_app.colaboradores.nuevo-manual'
import { Route as AppColaboradoresNuevoContratoRouteImport } from './routes/_app.colaboradores.nuevo-contrato'
import { Route as AppColaboradoresIdRouteImport } from './routes/_app.colaboradores.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRevisionRoute = AppRevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizacionRoute = AppOrganizacionRouteImport.update({
  id: '/organizacion',
  path: '/organizacion',
  getParentRoute: () => AppRoute,
} as any)
const AppObligacionesRoute = AppObligacionesRouteImport.update({
  id: '/obligaciones',
  path: '/obligaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditoriaRoute = AppAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRoute,
} as any)
const AppColaboradoresIndexRoute = AppColaboradoresIndexRouteImport.update({
  id: '/colaboradores/',
  path: '/colaboradores/',
  getParentRoute: () => AppRoute,
} as any)
const AppColaboradoresNuevoManualRoute =
  AppColaboradoresNuevoManualRouteImport.update({
    id: '/colaboradores/nuevo-manual',
    path: '/colaboradores/nuevo-manual',
    getParentRoute: () => AppRoute,
  } as any)
const AppColaboradoresNuevoContratoRoute =
  AppColaboradoresNuevoContratoRouteImport.update({
    id: '/colaboradores/nuevo-contrato',
    path: '/colaboradores/nuevo-contrato',
    getParentRoute: () => AppRoute,
  } as any)
const AppColaboradoresIdRoute = AppColaboradoresIdRouteImport.update({
  id: '/colaboradores/$id',
  path: '/colaboradores/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alertas': typeof AppAlertasRoute
  '/auditoria': typeof AppAuditoriaRoute
  '/dashboard': typeof AppDashboardRoute
  '/documentos': typeof AppDocumentosRoute
  '/obligaciones': typeof AppObligacionesRoute
  '/organizacion': typeof AppOrganizacionRoute
  '/revision': typeof AppRevisionRoute
  '/api/tts': typeof ApiTtsRoute
  '/colaboradores/$id': typeof AppColaboradoresIdRoute
  '/colaboradores/nuevo-contrato': typeof AppColaboradoresNuevoContratoRoute
  '/colaboradores/nuevo-manual': typeof AppColaboradoresNuevoManualRoute
  '/colaboradores/': typeof AppColaboradoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/alertas': typeof AppAlertasRoute
  '/auditoria': typeof AppAuditoriaRoute
  '/dashboard': typeof AppDashboardRoute
  '/documentos': typeof AppDocumentosRoute
  '/obligaciones': typeof AppObligacionesRoute
  '/organizacion': typeof AppOrganizacionRoute
  '/revision': typeof AppRevisionRoute
  '/api/tts': typeof ApiTtsRoute
  '/colaboradores/$id': typeof AppColaboradoresIdRoute
  '/colaboradores/nuevo-contrato': typeof AppColaboradoresNuevoContratoRoute
  '/colaboradores/nuevo-manual': typeof AppColaboradoresNuevoManualRoute
  '/colaboradores': typeof AppColaboradoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/alertas': typeof AppAlertasRoute
  '/_app/auditoria': typeof AppAuditoriaRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/documentos': typeof AppDocumentosRoute
  '/_app/obligaciones': typeof AppObligacionesRoute
  '/_app/organizacion': typeof AppOrganizacionRoute
  '/_app/revision': typeof AppRevisionRoute
  '/api/tts': typeof ApiTtsRoute
  '/_app/colaboradores/$id': typeof AppColaboradoresIdRoute
  '/_app/colaboradores/nuevo-contrato': typeof AppColaboradoresNuevoContratoRoute
  '/_app/colaboradores/nuevo-manual': typeof AppColaboradoresNuevoManualRoute
  '/_app/colaboradores/': typeof AppColaboradoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/alertas'
    | '/auditoria'
    | '/dashboard'
    | '/documentos'
    | '/obligaciones'
    | '/organizacion'
    | '/revision'
    | '/api/tts'
    | '/colaboradores/$id'
    | '/colaboradores/nuevo-contrato'
    | '/colaboradores/nuevo-manual'
    | '/colaboradores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/alertas'
    | '/auditoria'
    | '/dashboard'
    | '/documentos'
    | '/obligaciones'
    | '/organizacion'
    | '/revision'
    | '/api/tts'
    | '/colaboradores/$id'
    | '/colaboradores/nuevo-contrato'
    | '/colaboradores/nuevo-manual'
    | '/colaboradores'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/alertas'
    | '/_app/auditoria'
    | '/_app/dashboard'
    | '/_app/documentos'
    | '/_app/obligaciones'
    | '/_app/organizacion'
    | '/_app/revision'
    | '/api/tts'
    | '/_app/colaboradores/$id'
    | '/_app/colaboradores/nuevo-contrato'
    | '/_app/colaboradores/nuevo-manual'
    | '/_app/colaboradores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/revision': {
      id: '/_app/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof AppRevisionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/organizacion': {
      id: '/_app/organizacion'
      path: '/organizacion'
      fullPath: '/organizacion'
      preLoaderRoute: typeof AppOrganizacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/obligaciones': {
      id: '/_app/obligaciones'
      path: '/obligaciones'
      fullPath: '/obligaciones'
      preLoaderRoute: typeof AppObligacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documentos': {
      id: '/_app/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/auditoria': {
      id: '/_app/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AppAuditoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/alertas': {
      id: '/_app/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colaboradores/': {
      id: '/_app/colaboradores/'
      path: '/colaboradores'
      fullPath: '/colaboradores/'
      preLoaderRoute: typeof AppColaboradoresIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colaboradores/nuevo-manual': {
      id: '/_app/colaboradores/nuevo-manual'
      path: '/colaboradores/nuevo-manual'
      fullPath: '/colaboradores/nuevo-manual'
      preLoaderRoute: typeof AppColaboradoresNuevoManualRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colaboradores/nuevo-contrato': {
      id: '/_app/colaboradores/nuevo-contrato'
      path: '/colaboradores/nuevo-contrato'
      fullPath: '/colaboradores/nuevo-contrato'
      preLoaderRoute: typeof AppColaboradoresNuevoContratoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colaboradores/$id': {
      id: '/_app/colaboradores/$id'
      path: '/colaboradores/$id'
      fullPath: '/colaboradores/$id'
      preLoaderRoute: typeof AppColaboradoresIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertasRoute: typeof AppAlertasRoute
  AppAuditoriaRoute: typeof AppAuditoriaRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppObligacionesRoute: typeof AppObligacionesRoute
  AppOrganizacionRoute: typeof AppOrganizacionRoute
  AppRevisionRoute: typeof AppRevisionRoute
  AppColaboradoresIdRoute: typeof AppColaboradoresIdRoute
  AppColaboradoresNuevoContratoRoute: typeof AppColaboradoresNuevoContratoRoute
  AppColaboradoresNuevoManualRoute: typeof AppColaboradoresNuevoManualRoute
  AppColaboradoresIndexRoute: typeof AppColaboradoresIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertasRoute: AppAlertasRoute,
  AppAuditoriaRoute: AppAuditoriaRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppObligacionesRoute: AppObligacionesRoute,
  AppOrganizacionRoute: AppOrganizacionRoute,
  AppRevisionRoute: AppRevisionRoute,
  AppColaboradoresIdRoute: AppColaboradoresIdRoute,
  AppColaboradoresNuevoContratoRoute: AppColaboradoresNuevoContratoRoute,
  AppColaboradoresNuevoManualRoute: AppColaboradoresNuevoManualRoute,
  AppColaboradoresIndexRoute: AppColaboradoresIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
